### ISSUE TITLE
Error for Ajax-Calls with no JS/CSS attached

### ISSUE THREAD

**Issue by timhorstmann** [b13/http2#11]
https://github.com/b13/http2/commit/be8af93a7d93915ca8761e46536cc070cc3e932d
This refactoring causes a 500 error for me.

<img width="581" alt="78769795-143bc600-798e-11ea-8613-55cb39c85a3f" src="https://user-images.githubusercontent.com/5028717/87292040-7f9eb200-c500-11ea-87a9-9e50623c9b46.png">

In my case, i have an ajax-call with no css or js attached to $params.

Line 64 crashes with "array_unique() expects parameter 1 to be array, null given", because the key "scripts" does not exist.
Please add a proper check.

**Comment by ervaude** [comment]
Have you tried the latest release? This should be fixed in 1.0.2

**Comment by ervaude** [comment]
Duplicated #7
