### ISSUE TITLE
JavaScript Modules are not handled correctly

### ISSUE THREAD

**Issue by bavarianbytes** [b13/http2#28]
EcmaScript modules require a `rel=modulepreload` instead of `rel=preload`: https://web.dev/articles/modulepreload

It would be nice if the extension would reflect that. An simple approach would be to check if the file extension is `.mjs`. Something like this in `Classes/Http/ResourcePusher.php:addPreloadHeaderToResponse()`:

```php
if(str_contains($uri, '.mjs')) {
    return $response->withAddedHeader('Link', '<' . htmlspecialchars(PathUtility::getAbsoluteWebPath($uri)) . '>; rel=modulepreload; as=' . $type);
} else {
    return $response->withAddedHeader('Link', '<' . htmlspecialchars(PathUtility::getAbsoluteWebPath($uri)) . '>; rel=preload; as=' . $type);
}
```

**Comment by bmack** [comment]
sounds good, do you want to create a PR for that?

**Comment by bavarianbytes** [comment]
Done! :-)
