### ISSUE TITLE
PHP Fatal Error when page doesn't contain CSS and/or JS

### ISSUE THREAD

**Issue by hannesbochmann** [b13/http2#7]
If a page has no CSS and/or JS included a fatal PHP error is thrown.

array_unique() expects parameter 1 to be array, null given | TypeError thrown in file http2/Classes/PageRendererHook.php in line 64

The easiest solution would be an array cast in PageRendererHook line 64 and 65. I can provide a pull request.

**Comment by bmack** [comment]
Hey @hannesbochmann 

would be great to create a pull request!
